# Generated by Django 5.2.7 on 2025-11-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='logo',
        ),
        migrations.AddField(
            model_name='std',
            name='room_no',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
