# Generated by Django 5.2.7 on 2025-11-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_school_logo_std_room_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='std',
            name='room_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
